/**
 * DueDateHQ Drizzle schema.
 *
 * Design principles:
 * - Organization-based multi-tenancy from Day 1. Solo user = 1 org with 1 membership.
 *   Adding multi-seat later is zero schema-rewrite — just add memberships.
 * - audit_events is Day 1 table; agent-ready (actor_type supports "agent" / "cron").
 * - deadline_rules is versioned — IRS changes a rule, we keep the old version
 *   alongside the new one so historical records stay valid.
 * - deadline_instances is the per-entity materialized row (generated by service
 *   layer when a client/entity is created or rules change).
 */

import {
  pgTable,
  text,
  timestamp,
  date,
  boolean,
  integer,
  jsonb,
  index,
  uniqueIndex,
  pgEnum,
} from "drizzle-orm/pg-core";
import { nanoid } from "nanoid";

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const membershipRoleEnum = pgEnum("membership_role", [
  "owner",
  "admin",
  "member",
]);

export const entityTypeEnum = pgEnum("entity_type", [
  "individual",
  "c_corp",
  "s_corp",
  "partnership",
  "llc",
  "trust",
  "estate",
  "nonprofit",
]);

export const deadlineStatusEnum = pgEnum("deadline_status", [
  "pending",
  // 🆕 "I'm blocked on the client sending me docs". Most common blocked
  // state, was hidden under in_progress before. Splitting it out lets
  // the dashboard answer "what am I blocked on?" vs "what am I working on?".
  "waiting_on_client",
  "in_progress",
  // 🆕 "I'm done my prep work, just need signature / e-file ack".
  // Stops the "I thought we filed it" gap.
  "ready_to_file",
  "completed",
  "extended",
  "missed",
  "not_applicable",
]);

export const jurisdictionTypeEnum = pgEnum("jurisdiction_type", [
  "federal",
  "state",
  "city",
]);

export const ruleTypeEnum = pgEnum("rule_type", [
  "fixed_date",           // e.g., 4/15 every year
  "relative_to_year_end", // e.g., 3.5 months after FYE
  "quarterly_estimated",  // e.g., 4 quarters on specific dates
  "election_window",      // e.g., NY PTET must be elected by 3/15 — irrevocable
]);

export const actorTypeEnum = pgEnum("actor_type", [
  "user",
  "agent",
  "cron",
  "system",
]);

// ---------------------------------------------------------------------------
// Core tenancy
// ---------------------------------------------------------------------------

export const organizations = pgTable(
  "organizations",
  {
    id: text("id").primaryKey().$defaultFn(() => `org_${nanoid(12)}`),
    name: text("name").notNull(),
    plan: text("plan").notNull().default("beta"), // beta | solo | pro | team
    clerkOrgId: text("clerk_org_id").unique(), // nullable — solo users may not use Clerk Orgs yet
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("organizations_clerk_org_id_idx").on(t.clerkOrgId)],
);

export const users = pgTable(
  "users",
  {
    id: text("id").primaryKey().$defaultFn(() => `usr_${nanoid(12)}`),
    clerkUserId: text("clerk_user_id").notNull().unique(),
    email: text("email").notNull(),
    fullName: text("full_name"),
    timezone: text("timezone").notNull().default("America/New_York"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("users_email_idx").on(t.email)],
);

export const memberships = pgTable(
  "memberships",
  {
    id: text("id").primaryKey().$defaultFn(() => `mem_${nanoid(12)}`),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    role: membershipRoleEnum("role").notNull().default("owner"),
    /**
     * Per-membership iCal subscription token. Embedded in the public
     * URL the user pastes into Google Cal / Outlook / Apple Cal:
     *   https://duedate.hq/api/ical/<token>.ics
     *
     * NULL = subscription disabled. Generate by writing a 24-byte
     * base64url random; revoke by setting back to NULL; rotate by
     * overwriting with a new value (which immediately invalidates
     * the old URL — the next refresh from any subscribed client
     * will return 404 until they paste the new URL).
     *
     * UNIQUE-indexed so the unauthenticated GET endpoint can do a
     * single indexed read to resolve token → membership → org.
     * Postgres UNIQUE allows multiple NULLs, which is what we want.
     */
    icalToken: text("ical_token"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("memberships_user_org_idx").on(t.userId, t.orgId),
    index("memberships_org_idx").on(t.orgId),
    uniqueIndex("memberships_ical_token_idx").on(t.icalToken),
  ],
);

// ---------------------------------------------------------------------------
// Client / Entity domain
// ---------------------------------------------------------------------------

export const clients = pgTable(
  "clients",
  {
    id: text("id").primaryKey().$defaultFn(() => `cli_${nanoid(12)}`),
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    primaryContactEmail: text("primary_contact_email"),
    primaryContactPhone: text("primary_contact_phone"),
    notes: text("notes"),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("clients_org_idx").on(t.orgId),
    index("clients_org_archived_idx").on(t.orgId, t.archivedAt),
  ],
);

// ---------------------------------------------------------------------------
// Multiple contacts per client.
//
// CPAs send reminders / docs to more than one person at the client
// (CFO + bookkeeper + spouse + assistant). Modeling a single
// `primary_contact_email` on `clients` was sufficient for MVP-day-1 but
// punishingly thin once email cron started reaching real recipients.
//
// Design notes:
//   - `priority` is the sort key; priority=0 is the primary. We don't
//     enforce "exactly one primary" in the DB — service layer demotes
//     the previous primary when one is promoted. Race-window tradeoff:
//     a brief moment of two priority=0 rows is fine for read paths
//     (we display whichever sorts first by createdAt as the de facto
//     primary).
//   - Either `email` or `phone` must be present — checked in the
//     service layer; no DB CHECK because future channels (Slack, IM)
//     may ride on this table too.
//   - `receives_reminders` is the toggle that the email cron will
//     consult once Round B wires in real sending. Default true.
//   - `clients.primary_contact_email/phone` stay as a denormalized
//     cache so existing search / CSV / dashboard queries keep working
//     without rewrite. Service layer keeps them in sync.
// ---------------------------------------------------------------------------

export const clientContacts = pgTable(
  "client_contacts",
  {
    id: text("id").primaryKey().$defaultFn(() => `con_${nanoid(12)}`),
    clientId: text("client_id").notNull().references(() => clients.id, {
      onDelete: "cascade",
    }),
    orgId: text("org_id").notNull().references(() => organizations.id, {
      onDelete: "cascade",
    }),
    name: text("name"),
    email: text("email"),
    phone: text("phone"),
    /** Free text for now — "owner", "cfo", "bookkeeper", "spouse",
        "assistant", "controller", "advisor", whatever. UI surfaces a
        suggestions list but doesn't lock down the value. */
    role: text("role"),
    /** 0 = primary contact. 1+ = secondary, in display order. */
    priority: integer("priority").notNull().default(100),
    /** Will the per-deadline reminder cron email this contact? */
    receivesReminders: boolean("receives_reminders").notNull().default(true),
    notes: text("notes"),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("client_contacts_client_idx").on(t.clientId),
    index("client_contacts_client_priority_idx").on(t.clientId, t.priority),
  ],
);

export const entities = pgTable(
  "entities",
  {
    id: text("id").primaryKey().$defaultFn(() => `ent_${nanoid(12)}`),
    clientId: text("client_id").notNull().references(() => clients.id, { onDelete: "cascade" }),
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    name: text("name").notNull(), // e.g., "John Smith", "Smith Holdings LLC"
    entityType: entityTypeEnum("entity_type").notNull(),
    ein: text("ein"), // or SSN for individuals — encrypt at rest in V2
    homeState: text("home_state"), // ISO state code "CA", "NY", etc.
    operatingStates: jsonb("operating_states").$type<string[]>().notNull().default([]),
    fiscalYearEnd: text("fiscal_year_end").notNull().default("12-31"), // MM-DD
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("entities_org_idx").on(t.orgId),
    index("entities_client_idx").on(t.clientId),
  ],
);

// ---------------------------------------------------------------------------
// Deadline rule catalog (seed data — we maintain it centrally)
// ---------------------------------------------------------------------------

export const deadlineRules = pgTable(
  "deadline_rules",
  {
    id: text("id").primaryKey().$defaultFn(() => `rul_${nanoid(12)}`),
    jurisdictionType: jurisdictionTypeEnum("jurisdiction_type").notNull(),
    jurisdictionCode: text("jurisdiction_code").notNull(), // "federal" | "CA" | "NY" | "TX" | "DE" | "NJ"
    formCode: text("form_code").notNull(), // "1040", "1120-S", "IT-201", "3804", etc.
    title: text("title").notNull(), // human-readable
    description: text("description"),
    entityTypes: jsonb("entity_types").$type<string[]>().notNull(), // which entity_type enums this rule applies to
    ruleType: ruleTypeEnum("rule_type").notNull(),
    rulePayload: jsonb("rule_payload").notNull(), // flexible date logic — see ruleType
    extensionFormCode: text("extension_form_code"),
    extensionPayload: jsonb("extension_payload"),
    penaltySummary: text("penalty_summary"),
    sourceUrl: text("source_url").notNull(),
    version: integer("version").notNull().default(1),
    effectiveFrom: date("effective_from").notNull(),
    effectiveTo: date("effective_to"), // null = currently active
    irrevocable: boolean("irrevocable").notNull().default(false), // e.g., NY PTET 3/15
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("deadline_rules_jurisdiction_idx").on(t.jurisdictionType, t.jurisdictionCode),
    index("deadline_rules_form_idx").on(t.formCode),
    // Natural key — without this, re-running db:seed silently duplicates
    // every existing rule because onConflictDoNothing() has no target to
    // match against. Title is included in the key so we can evolve the
    // wording of an existing rule by bumping `version`.
    uniqueIndex("deadline_rules_natural_key_idx").on(
      t.jurisdictionCode,
      t.formCode,
      t.title,
      t.version,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Per-entity deadline instances (materialized from rules)
// ---------------------------------------------------------------------------

export const deadlineInstances = pgTable(
  "deadline_instances",
  {
    id: text("id").primaryKey().$defaultFn(() => `dl_${nanoid(12)}`),
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    entityId: text("entity_id").notNull().references(() => entities.id, { onDelete: "cascade" }),
    ruleId: text("rule_id").notNull().references(() => deadlineRules.id),
    taxYear: integer("tax_year").notNull(), // e.g., 2025 (for returns filed in 2026)
    dueDate: date("due_date").notNull(),
    status: deadlineStatusEnum("status").notNull().default("pending"),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    completedByUserId: text("completed_by_user_id").references(() => users.id),
    completedByActorType: actorTypeEnum("completed_by_actor_type"),
    extensionFiledAt: timestamp("extension_filed_at", { withTimezone: true }),
    extensionDueDate: date("extension_due_date"),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("deadline_instances_org_due_idx").on(t.orgId, t.dueDate, t.status),
    index("deadline_instances_entity_idx").on(t.entityId),
    index("deadline_instances_org_status_idx").on(t.orgId, t.status),
    uniqueIndex("deadline_instances_unique_idx").on(t.entityId, t.ruleId, t.taxYear),
  ],
);

// ---------------------------------------------------------------------------
// Reminders sent (dedupe — never send same 14-day reminder twice)
// ---------------------------------------------------------------------------

export const remindersSent = pgTable(
  "reminders_sent",
  {
    id: text("id").primaryKey().$defaultFn(() => `rem_${nanoid(12)}`),
    deadlineInstanceId: text("deadline_instance_id")
      .notNull()
      .references(() => deadlineInstances.id, { onDelete: "cascade" }),
    daysBeforeDue: integer("days_before_due").notNull(), // 30 | 14 | 3 | 1
    channel: text("channel").notNull(), // "email" for MVP, "sms" V2
    sentToEmail: text("sent_to_email"),
    sentAt: timestamp("sent_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("reminders_dedupe_idx").on(
      t.deadlineInstanceId,
      t.daysBeforeDue,
      t.channel,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Weekly digest sends (idempotent — second cron tick this week is a no-op)
//
// Identified by ISO week (e.g., "2026-W17") so the dedupe boundary lines
// up with how a CPA mentally schedules. If we change cadence later we
// can add a `digest_type` discriminator on the unique index.
// ---------------------------------------------------------------------------

export const digestSends = pgTable(
  "digest_sends",
  {
    id: text("id").primaryKey().$defaultFn(() => `dig_${nanoid(12)}`),
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    /** ISO 8601 week — e.g. "2026-W17". One digest per (user, week, type). */
    weekKey: text("week_key").notNull(),
    digestType: text("digest_type").notNull().default("weekly"),
    recipientEmail: text("recipient_email").notNull(),
    deadlineCount: integer("deadline_count").notNull().default(0),
    urgentCount: integer("urgent_count").notNull().default(0),
    /** AI-generated one-liner ("This week's heavier than usual…"). */
    aiSummary: text("ai_summary"),
    /** Resend message id, for clickthrough debugging. */
    providerMessageId: text("provider_message_id"),
    sentAt: timestamp("sent_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("digest_sends_user_week_idx").on(
      t.userId,
      t.weekKey,
      t.digestType,
    ),
    index("digest_sends_org_idx").on(t.orgId),
  ],
);

// ---------------------------------------------------------------------------
// Tax-authority announcements — IRS Newsroom + state DOR feeds.
//
// Org-agnostic on purpose: an IRS hurricane relief notice is identical
// for every CPA, so we store it once and let each org's UI compute
// "does this affect any of my clients?" on read by intersecting
// `affected_jurisdictions` with the org's clients' home states.
//
// Idempotency: `external_id` (RSS GUID / canonical link) is unique. The
// scrape workflow runs daily; second-run hits ON CONFLICT DO NOTHING.
// ---------------------------------------------------------------------------

export const announcements = pgTable(
  "announcements",
  {
    id: text("id").primaryKey().$defaultFn(() => `ann_${nanoid(12)}`),
    /** Origin feed — "irs_newsroom" today, state DORs in V2. */
    source: text("source").notNull(),
    /** RSS GUID or canonical URL — guaranteed unique per source. */
    externalId: text("external_id").notNull(),
    title: text("title").notNull(),
    summary: text("summary"),
    url: text("url").notNull(),
    publishedAt: timestamp("published_at", { withTimezone: true }).notNull(),

    /** AI classification — see ANNOUNCEMENT_CATEGORIES below. */
    category: text("category").notNull().default("general"),
    /** AI extraction — ["federal"] or ["FL", "TX"] or [] when unclear. */
    affectedJurisdictions: jsonb("affected_jurisdictions")
      .$type<string[]>()
      .notNull()
      .default([]),
    /** AI relevance score 1–5; bell only fires for >= 4. */
    relevanceScore: integer("relevance_score").notNull().default(3),
    /** AI one-line summary in CPA-friendly language. */
    aiSummary: text("ai_summary"),

    /**
     * Structured AI extraction layer (Round C).
     *
     * The original `affectedJurisdictions` (state codes only) is too
     * coarse — "FL hurricane" matched all FL clients including ones
     * who have no deadlines in the relief window. These four fields
     * narrow the match to exactly the affected work:
     *
     *   - affectedFormCodes: form codes the announcement specifically
     *     names (["1040", "1120", "941"]). Empty when "all returns".
     *   - originalDeadlineStart/End: ISO date range that the
     *     announcement is postponing (e.g. "deadlines from Aug 5
     *     through Feb 3"). NULL when not a date-postponement item.
     *   - reliefDeadline: the new postponed date (e.g. "moved to
     *     Feb 3, 2026"). NULL when not applicable.
     *
     * All four are nullable / empty by default so older rows still
     * work without backfill, and AI failures gracefully degrade to
     * the coarse state-only match.
     */
    affectedFormCodes: jsonb("affected_form_codes")
      .$type<string[]>()
      .notNull()
      .default([]),
    originalDeadlineStart: text("original_deadline_start"), // YYYY-MM-DD
    originalDeadlineEnd: text("original_deadline_end"),     // YYYY-MM-DD
    reliefDeadline: text("relief_deadline"),                // YYYY-MM-DD

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("announcements_source_external_idx").on(
      t.source,
      t.externalId,
    ),
    index("announcements_published_idx").on(t.publishedAt),
    index("announcements_score_published_idx").on(
      t.relevanceScore,
      t.publishedAt,
    ),
  ],
);

export const ANNOUNCEMENT_CATEGORIES = [
  "disaster_relief", // IRS extends deadline for storm/wildfire victims
  "form_change",     // Form 1099-K threshold change, new schedule, etc.
  "procedural",      // E-file requirement, filing-method change
  "general",         // Everything else / lowest priority
] as const;

// ---------------------------------------------------------------------------
// Per-user dismiss state for announcements.
//
// Lets a CPA close an announcement they've read so it stops claiming
// dashboard real estate. Per-USER (not per-org) — for solo persona this
// is the same thing, and for multi-seat firms it's actually the right
// primitive (partner A's "I've read this" shouldn't hide it from
// partner B who hasn't).
//
// Source-of-truth announcements stay intact; this is purely a view filter.
// Reversible — un-dismiss simply deletes the row.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Per-client review state for an announcement.
//
// When a deadline-affecting IRS announcement ("FL hurricane disaster
// relief, deadline postponed") matches some of the org's clients, the
// CPA's actual workflow is: walk through each affected client one by
// one, decide what to do. This table tracks "I've reviewed Anderson
// for this announcement" so the CPA can come back tomorrow and pick
// up where they left off.
//
// Per-USER (not per-org). Per-ORG would mean partner A acking
// "reviewed" hides it from partner B who hasn't looked. Wrong primitive.
// ---------------------------------------------------------------------------

export const announcementClientAcks = pgTable(
  "announcement_client_acks",
  {
    id: text("id").primaryKey().$defaultFn(() => `ack_${nanoid(12)}`),
    userId: text("user_id").notNull().references(() => users.id, {
      onDelete: "cascade",
    }),
    announcementId: text("announcement_id").notNull().references(
      () => announcements.id,
      { onDelete: "cascade" },
    ),
    clientId: text("client_id").notNull().references(() => clients.id, {
      onDelete: "cascade",
    }),
    ackedAt: timestamp("acked_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("ann_client_ack_user_ann_client_idx").on(
      t.userId,
      t.announcementId,
      t.clientId,
    ),
    index("ann_client_ack_ann_user_idx").on(t.announcementId, t.userId),
  ],
);

export const announcementDismissals = pgTable(
  "announcement_dismissals",
  {
    id: text("id").primaryKey().$defaultFn(() => `dis_${nanoid(12)}`),
    userId: text("user_id").notNull().references(() => users.id, {
      onDelete: "cascade",
    }),
    announcementId: text("announcement_id").notNull().references(
      () => announcements.id,
      { onDelete: "cascade" },
    ),
    dismissedAt: timestamp("dismissed_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // One dismiss per (user, announcement). Repeat clicks are no-ops.
    uniqueIndex("announcement_dismissals_user_ann_idx").on(
      t.userId,
      t.announcementId,
    ),
    // Anti-join from announcements list filter.
    index("announcement_dismissals_user_idx").on(t.userId),
  ],
);

// ---------------------------------------------------------------------------
// Audit log (Day 1 — invisible to users in MVP, visible in V2 small-firm tier)
// ---------------------------------------------------------------------------

export const auditEvents = pgTable(
  "audit_events",
  {
    id: text("id").primaryKey().$defaultFn(() => `aud_${nanoid(16)}`),
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    actorType: actorTypeEnum("actor_type").notNull(),
    actorId: text("actor_id"), // user_id OR agent identifier OR "cron"
    action: text("action").notNull(), // "client.created", "deadline.completed", etc.
    targetType: text("target_type").notNull(), // "client" | "entity" | "deadline_instance" | ...
    targetId: text("target_id").notNull(),
    payload: jsonb("payload").$type<Record<string, unknown>>(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("audit_events_org_time_idx").on(t.orgId, t.occurredAt),
    index("audit_events_target_idx").on(t.targetType, t.targetId),
  ],
);

// ---------------------------------------------------------------------------
// Type exports
// ---------------------------------------------------------------------------

export type Organization = typeof organizations.$inferSelect;
export type NewOrganization = typeof organizations.$inferInsert;
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Membership = typeof memberships.$inferSelect;
export type Client = typeof clients.$inferSelect;
export type NewClient = typeof clients.$inferInsert;
export type Entity = typeof entities.$inferSelect;
export type NewEntity = typeof entities.$inferInsert;
export type DeadlineRule = typeof deadlineRules.$inferSelect;
export type DeadlineInstance = typeof deadlineInstances.$inferSelect;
export type NewDeadlineInstance = typeof deadlineInstances.$inferInsert;
export type AuditEvent = typeof auditEvents.$inferSelect;
export type NewAuditEvent = typeof auditEvents.$inferInsert;
export type DigestSend = typeof digestSends.$inferSelect;
export type NewDigestSend = typeof digestSends.$inferInsert;
export type Announcement = typeof announcements.$inferSelect;
export type NewAnnouncement = typeof announcements.$inferInsert;
export type AnnouncementDismissal = typeof announcementDismissals.$inferSelect;
export type AnnouncementClientAck = typeof announcementClientAcks.$inferSelect;
export type ClientContact = typeof clientContacts.$inferSelect;
export type NewClientContact = typeof clientContacts.$inferInsert;
