/**
 * DueDateHQ Drizzle schema.
 *
 * Design principles:
 * - Organization-based multi-tenancy from Day 1. Solo user = 1 org with 1 membership.
 *   Adding multi-seat later is zero schema-rewrite — just add memberships.
 * - audit_events is Day 1 table; agent-ready (actor_type supports "agent" / "cron").
 * - deadline_rules is versioned — IRS changes a rule, we keep the old version
 *   alongside the new one so historical records stay valid.
 * - deadline_instances is the per-entity materialized row (generated by service
 *   layer when a client/entity is created or rules change).
 */

import {
  pgTable,
  text,
  timestamp,
  date,
  boolean,
  integer,
  jsonb,
  index,
  uniqueIndex,
  unique,
  pgEnum,
  primaryKey,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { nanoid } from "nanoid";

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const membershipRoleEnum = pgEnum("membership_role", [
  "owner",
  "admin",
  "member",
]);

export const invitationStatusEnum = pgEnum("invitation_status", [
  "pending",
  "accepted",
  "revoked",
  "expired",
]);

export const entityTypeEnum = pgEnum("entity_type", [
  "individual",
  "c_corp",
  "s_corp",
  "partnership",
  "llc",
  "trust",
  "estate",
  "nonprofit",
]);

// Deadline workflow status was removed 2026-05-01. State is now derived
// purely from `completed_at` (NULL = pending, NOT NULL = filed). The
// owner_user_id field tells you who's on it; notes carry "what they're
// blocked on" detail. Three motivations for the collapse:
//
//   1. CPA interviewees consistently said the in-progress / waiting-on-
//      client / ready-to-file distinctions added clicks without changing
//      their next action.
//   2. Status was redundant with completed_at — the two could disagree
//      after a write race, and we only ever cared about "is it done?".
//   3. Owner + notes is a simpler, more flexible coordination primitive
//      for small teams than a fixed workflow enum.
//
// The deadlineStatusEnum and `status` column were dropped. Historical
// audit_events with action="deadline.status_changed" remain valid for
// timeline display but no new rows are written.

export const jurisdictionTypeEnum = pgEnum("jurisdiction_type", [
  "federal",
  "state",
  "city",
]);

export const ruleTypeEnum = pgEnum("rule_type", [
  "fixed_date",           // e.g., 4/15 every year
  "relative_to_year_end", // e.g., 3.5 months after FYE
  "quarterly_estimated",  // e.g., 4 quarters on specific dates
  "election_window",      // e.g., NY PTET must be elected by 3/15 — irrevocable
]);

export const actorTypeEnum = pgEnum("actor_type", [
  "user",
  "agent",
  "cron",
  "system",
]);

// ---------------------------------------------------------------------------
// Core tenancy
// ---------------------------------------------------------------------------

export const organizations = pgTable(
  "organizations",
  {
    id: text("id").primaryKey().$defaultFn(() => `org_${nanoid(12)}`),
    name: text("name").notNull(),
    plan: text("plan").notNull().default("beta"), // beta | solo | pro | team
    clerkOrgId: text("clerk_org_id").unique(), // nullable — solo users may not use Clerk Orgs yet
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("organizations_clerk_org_id_idx").on(t.clerkOrgId)],
);

export const users = pgTable(
  "users",
  {
    id: text("id").primaryKey().$defaultFn(() => `usr_${nanoid(12)}`),
    clerkUserId: text("clerk_user_id").notNull().unique(),
    email: text("email").notNull(),
    fullName: text("full_name"),
    timezone: text("timezone").notNull().default("America/New_York"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("users_email_idx").on(t.email)],
);

export const memberships = pgTable(
  "memberships",
  {
    id: text("id").primaryKey().$defaultFn(() => `mem_${nanoid(12)}`),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    role: membershipRoleEnum("role").notNull().default("owner"),
    /**
     * Per-membership iCal subscription token. Embedded in the public
     * URL the user pastes into Google Cal / Outlook / Apple Cal:
     *   https://duedate.hq/api/ical/<token>.ics
     *
     * NULL = subscription disabled. Generate by writing a 24-byte
     * base64url random; revoke by setting back to NULL; rotate by
     * overwriting with a new value (which immediately invalidates
     * the old URL — the next refresh from any subscribed client
     * will return 404 until they paste the new URL).
     *
     * UNIQUE-indexed so the unauthenticated GET endpoint can do a
     * single indexed read to resolve token → membership → org.
     * Postgres UNIQUE allows multiple NULLs, which is what we want.
     */
    icalToken: text("ical_token"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("memberships_user_org_idx").on(t.userId, t.orgId),
    index("memberships_org_idx").on(t.orgId),
    uniqueIndex("memberships_ical_token_idx").on(t.icalToken),
  ],
);

// ---------------------------------------------------------------------------
// Client / Entity domain
// ---------------------------------------------------------------------------

export const clients = pgTable(
  "clients",
  {
    id: text("id").primaryKey().$defaultFn(() => `cli_${nanoid(12)}`),
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    primaryContactEmail: text("primary_contact_email"),
    primaryContactPhone: text("primary_contact_phone"),
    notes: text("notes"),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("clients_org_idx").on(t.orgId),
    index("clients_org_archived_idx").on(t.orgId, t.archivedAt),
  ],
);

// ---------------------------------------------------------------------------
// Multiple contacts per client.
//
// CPAs send reminders / docs to more than one person at the client
// (CFO + bookkeeper + spouse + assistant). Modeling a single
// `primary_contact_email` on `clients` was sufficient for MVP-day-1 but
// punishingly thin once email cron started reaching real recipients.
//
// Design notes:
//   - `priority` is the sort key; priority=0 is the primary. We don't
//     enforce "exactly one primary" in the DB — service layer demotes
//     the previous primary when one is promoted. Race-window tradeoff:
//     a brief moment of two priority=0 rows is fine for read paths
//     (we display whichever sorts first by createdAt as the de facto
//     primary).
//   - Either `email` or `phone` must be present — checked in the
//     service layer; no DB CHECK because future channels (Slack, IM)
//     may ride on this table too.
//   - `receives_reminders` is the toggle that the email cron will
//     consult once Round B wires in real sending. Default true.
//   - `clients.primary_contact_email/phone` stay as a denormalized
//     cache so existing search / CSV / dashboard queries keep working
//     without rewrite. Service layer keeps them in sync.
// ---------------------------------------------------------------------------

export const clientContacts = pgTable(
  "client_contacts",
  {
    id: text("id").primaryKey().$defaultFn(() => `con_${nanoid(12)}`),
    clientId: text("client_id").notNull().references(() => clients.id, {
      onDelete: "cascade",
    }),
    orgId: text("org_id").notNull().references(() => organizations.id, {
      onDelete: "cascade",
    }),
    name: text("name"),
    email: text("email"),
    phone: text("phone"),
    /** Free text for now — "owner", "cfo", "bookkeeper", "spouse",
        "assistant", "controller", "advisor", whatever. UI surfaces a
        suggestions list but doesn't lock down the value. */
    role: text("role"),
    /** 0 = primary contact. 1+ = secondary, in display order. */
    priority: integer("priority").notNull().default(100),
    /** Will the per-deadline reminder cron email this contact? */
    receivesReminders: boolean("receives_reminders").notNull().default(true),
    notes: text("notes"),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("client_contacts_client_idx").on(t.clientId),
    index("client_contacts_client_priority_idx").on(t.clientId, t.priority),
  ],
);

export const entities = pgTable(
  "entities",
  {
    id: text("id").primaryKey().$defaultFn(() => `ent_${nanoid(12)}`),
    clientId: text("client_id").notNull().references(() => clients.id, { onDelete: "cascade" }),
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    name: text("name").notNull(), // e.g., "John Smith", "Smith Holdings LLC"
    entityType: entityTypeEnum("entity_type").notNull(),
    ein: text("ein"), // or SSN for individuals — encrypt at rest in V2
    homeState: text("home_state"), // ISO state code "CA", "NY", etc.
    operatingStates: jsonb("operating_states").$type<string[]>().notNull().default([]),
    fiscalYearEnd: text("fiscal_year_end").notNull().default("12-31"), // MM-DD
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("entities_org_idx").on(t.orgId),
    index("entities_client_idx").on(t.clientId),
  ],
);

// ---------------------------------------------------------------------------
// Entity tax elections — opt-in flags per (entity, jurisdiction) that
// gate the visibility of election-only deadline rules (currently PTE).
//
// Hard-delete on revoke for v1 — election history isn't load-bearing
// yet. If a CPA needs "elected in 2025, revoked in 2027" semantics
// later, add `revokedAt` and switch to soft-delete.
// ---------------------------------------------------------------------------

export const entityElections = pgTable(
  "entity_elections",
  {
    id: text("id").primaryKey().$defaultFn(() => `eel_${nanoid(12)}`),
    entityId: text("entity_id").notNull().references(() => entities.id, {
      onDelete: "cascade",
    }),
    orgId: text("org_id").notNull().references(() => organizations.id, {
      onDelete: "cascade",
    }),
    /** State code matching `deadline_rules.jurisdiction_code` ("CA", "NY", …). */
    jurisdictionCode: text("jurisdiction_code").notNull(),
    /** Election kind. Only "pte" today; future: "qsub", "composite", etc. */
    kind: text("kind").notNull(),
    electedAt: timestamp("elected_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // One election per (entity, jurisdiction, kind). Repeat marks are no-ops.
    uniqueIndex("entity_elections_unique_idx").on(
      t.entityId,
      t.jurisdictionCode,
      t.kind,
    ),
    index("entity_elections_entity_idx").on(t.entityId),
    index("entity_elections_org_idx").on(t.orgId),
  ],
);

// ---------------------------------------------------------------------------
// Deadline rule catalog (seed data — we maintain it centrally)
// ---------------------------------------------------------------------------

export const deadlineRules = pgTable(
  "deadline_rules",
  {
    id: text("id").primaryKey().$defaultFn(() => `rul_${nanoid(12)}`),
    jurisdictionType: jurisdictionTypeEnum("jurisdiction_type").notNull(),
    jurisdictionCode: text("jurisdiction_code").notNull(), // "federal" | "CA" | "NY" | "TX" | "DE" | "NJ"
    formCode: text("form_code").notNull(), // "1040", "1120-S", "IT-201", "3804", etc.
    title: text("title").notNull(), // human-readable
    description: text("description"),
    entityTypes: jsonb("entity_types").$type<string[]>().notNull(), // which entity_type enums this rule applies to
    ruleType: ruleTypeEnum("rule_type").notNull(),
    rulePayload: jsonb("rule_payload").notNull(), // flexible date logic — see ruleType
    extensionFormCode: text("extension_form_code"),
    extensionPayload: jsonb("extension_payload"),
    penaltySummary: text("penalty_summary"),
    sourceUrl: text("source_url").notNull(),
    version: integer("version").notNull().default(1),
    effectiveFrom: date("effective_from").notNull(),
    effectiveTo: date("effective_to"), // null = currently active
    irrevocable: boolean("irrevocable").notNull().default(false), // e.g., NY PTET 3/15
    /**
     * When set (currently only "pte"), this rule is gated on the entity
     * having a matching record in `entity_elections`. NULL means the
     * rule always surfaces for any matching (entity_type, jurisdiction).
     *
     * Why: PTE elections are opt-in per-entity per-state. A CA LLC that
     * doesn't elect doesn't want CA-3893 cluttering their deadline list;
     * once they mark "PTE elected in CA", the rule starts surfacing.
     */
    requiresElection: text("requires_election"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("deadline_rules_jurisdiction_idx").on(t.jurisdictionType, t.jurisdictionCode),
    index("deadline_rules_form_idx").on(t.formCode),
    // Natural key — without this, re-running db:seed silently duplicates
    // every existing rule because onConflictDoNothing() has no target to
    // match against. Title is included in the key so we can evolve the
    // wording of an existing rule by bumping `version`.
    uniqueIndex("deadline_rules_natural_key_idx").on(
      t.jurisdictionCode,
      t.formCode,
      t.title,
      t.version,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Service groups — bundles of rules that get applied as a unit when a CPA
// onboards a client. The mental model: "Acme Corp gets Personal Tax Filing
// + Quarterly Payroll" rather than "Acme Corp is an individual so they get
// every rule that mentions individual". This is FIT's "service codes"
// concept, retooled.
//
// Two reasons services exist:
//   1. NOISE CONTROL — adding 941 quarterly rules for every employer means
//      individuals (who don't file 941) shouldn't see them. Services let us
//      add many rules without flooding clients who don't need them.
//   2. CPA INTENT — a sole proprietor with employees is "individual" entity
//      type but DOES need 941. The entity type alone can't express that;
//      a service can.
//
// Built-in services have org_id = NULL and a stable slug (e.g.
// `personal_tax`); firms get to use them as-is. V2 will let firms clone /
// customize built-ins by inserting their own org_id row.
// ---------------------------------------------------------------------------

export const serviceGroups = pgTable(
  "service_groups",
  {
    id: text("id").primaryKey().$defaultFn(() => `svc_${nanoid(12)}`),
    /** NULL = built-in / system-provided. Set = firm-customized service. */
    orgId: text("org_id").references(() => organizations.id, {
      onDelete: "cascade",
    }),
    /** Stable identifier used to reference services from seed/code
     *  ("personal_tax", "quarterly_payroll"). Lets the seeder upsert
     *  without UUIDs leaking. */
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    /** Auto-pre-check this service when a CPA adds an entity of these
     *  types. e.g. "personal_tax" defaults for ["individual"]. Empty
     *  array = opt-in only (CPA must check it manually). */
    defaultForEntityTypes: jsonb("default_for_entity_types")
      .$type<string[]>()
      .notNull()
      .default([]),
    /** Sort order in the UI picker — lower comes first. Lets us put
     *  the most common services up top. */
    sortOrder: integer("sort_order").notNull().default(100),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // Slug is unique per org (NULL allowed for built-ins; PG treats
    // multiple NULLs as distinct so no collision on built-in vs custom).
    uniqueIndex("service_groups_slug_org_idx").on(t.slug, t.orgId),
    index("service_groups_org_idx").on(t.orgId),
  ],
);

/**
 * Many-to-many: which deadline rules belong to which service. A 941
 * quarterly rule is in `quarterly_payroll`; a 1040 rule is in
 * `personal_tax`. The same rule CAN be in multiple services (e.g. a
 * state 1040 might live in both "personal_tax" and a state-specific
 * bundle), so we use a join table rather than an array column.
 */
export const serviceGroupRules = pgTable(
  "service_group_rules",
  {
    serviceGroupId: text("service_group_id")
      .notNull()
      .references(() => serviceGroups.id, { onDelete: "cascade" }),
    ruleId: text("rule_id")
      .notNull()
      .references(() => deadlineRules.id, { onDelete: "cascade" }),
  },
  (t) => [
    primaryKey({ columns: [t.serviceGroupId, t.ruleId] }),
    index("service_group_rules_rule_idx").on(t.ruleId),
  ],
);

/**
 * Which services are active for which entity. Soft-deleted via
 * removed_at so we can later support "show service history" without
 * losing past assignments. Uniqueness on active rows is enforced via
 * a partial index (entity, service) WHERE removed_at IS NULL.
 */
export const entityServices = pgTable(
  "entity_services",
  {
    id: text("id").primaryKey().$defaultFn(() => `esv_${nanoid(12)}`),
    entityId: text("entity_id")
      .notNull()
      .references(() => entities.id, { onDelete: "cascade" }),
    serviceGroupId: text("service_group_id")
      .notNull()
      .references(() => serviceGroups.id, { onDelete: "cascade" }),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    addedAt: timestamp("added_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    removedAt: timestamp("removed_at", { withTimezone: true }),
  },
  (t) => [
    // Active assignments are unique per (entity, service). We allow
    // multiple historical rows where removed_at is set, so a CPA who
    // toggles a service off and back on doesn't lose history.
    uniqueIndex("entity_services_active_idx")
      .on(t.entityId, t.serviceGroupId)
      .where(sql`${t.removedAt} IS NULL`),
    index("entity_services_entity_idx").on(t.entityId),
    index("entity_services_org_idx").on(t.orgId),
  ],
);

// ---------------------------------------------------------------------------
// Per-entity deadline instances (materialized from rules)
// ---------------------------------------------------------------------------

export const deadlineInstances = pgTable(
  "deadline_instances",
  {
    id: text("id").primaryKey().$defaultFn(() => `dl_${nanoid(12)}`),
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    entityId: text("entity_id").notNull().references(() => entities.id, { onDelete: "cascade" }),
    ruleId: text("rule_id").notNull().references(() => deadlineRules.id),
    taxYear: integer("tax_year").notNull(), // e.g., 2025 (for returns filed in 2026)
    dueDate: date("due_date").notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    completedByUserId: text("completed_by_user_id").references(() => users.id),
    completedByActorType: actorTypeEnum("completed_by_actor_type"),
    extensionFiledAt: timestamp("extension_filed_at", { withTimezone: true }),
    extensionDueDate: date("extension_due_date"),
    /**
     * True when an extension has been filed for this deadline.
     *
     * Replaces the old status='extended' enum value. "Extended" is a
     * date-shifted state, not a workflow stage — the CPA still has to
     * progress pending → in_progress → completed against the new
     * extensionDueDate. Storing it as a boolean lets `status` represent
     * pure workflow progress without conflating the two dimensions.
     */
    isExtended: boolean("is_extended").notNull().default(false),
    /**
     * Member of the org responsible for this deadline. NULL = unassigned
     * ("in queue, anyone can pick it up"). ON DELETE SET NULL so removing
     * a teammate doesn't drop their deadlines — they revert to unassigned
     * and someone else can claim them.
     *
     * Auto-default is intentionally absent: new deadlines start unassigned
     * even when the entity is created by a specific user, so a 5-person
     * small firm doesn't auto-dump 80 deadlines onto one person's queue.
     * The CPA explicitly assigns from the detail page or via a future
     * bulk-assign tool.
     */
    ownerUserId: text("owner_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("deadline_instances_org_due_idx").on(t.orgId, t.dueDate),
    index("deadline_instances_entity_idx").on(t.entityId),
    // Composite (org, completed_at) covers the most common dashboard
    // query: "open deadlines for this org" → WHERE completed_at IS NULL.
    index("deadline_instances_org_completed_idx").on(t.orgId, t.completedAt),
    // "Show me my deadlines" is the highest-frequency query for team
    // users — composite (org, owner) covers it without a full scan.
    index("deadline_instances_org_owner_idx").on(t.orgId, t.ownerUserId),
    uniqueIndex("deadline_instances_unique_idx").on(t.entityId, t.ruleId, t.taxYear),
  ],
);

// ---------------------------------------------------------------------------
// Deadline sub-tasks (prep stages — user-defined timeline nodes)
//
// Each row is one stage on the path from "today" to the deadline due
// date — e.g. "initial meeting", "docs requested", "internal review".
// Stages are user-defined (no canonical preset list); the deadline
// owner adds whatever nodes match their workflow for this filing.
//
// Why a separate table (vs jsonb on deadline_instances):
// - Stages are first-class queryable objects: dashboard surfaces "next
//   up" across deadlines, weekly digest groups by stage owner, badge
//   counts overdue stages — all of these need indexes, not a json scan.
// - Per-stage owner_user_id needs a FK with ON DELETE SET NULL so a
//   teammate leaving doesn't orphan the stage.
// - Audit history of stage completions wants its own row in
//   audit_events linked back to a stable id.
//
// Calendar / ICS rule: stages NEVER export. Only the parent deadline's
// due_date appears in the ICS feed. Stages are internal prep work; the
// deadline is the public commitment. See ui-samples/m-subtimeline-variants.html.
// ---------------------------------------------------------------------------

export const deadlineSubtasks = pgTable(
  "deadline_subtasks",
  {
    id: text("id").primaryKey().$defaultFn(() => `sub_${nanoid(12)}`),
    /**
     * Cascade-delete with the parent deadline so removing a deadline
     * doesn't leak stage rows. The CPA explicitly archives clients/
     * entities to clean up; that path already drops deadlines.
     */
    deadlineInstanceId: text("deadline_instance_id")
      .notNull()
      .references(() => deadlineInstances.id, { onDelete: "cascade" }),
    /**
     * Denormalized for cheap row-level org isolation in queries.
     * Without this every dashboard "show my open stages" query needs
     * a 3-table join (subtasks → instances → orgs); with it we can
     * filter directly. Service layer keeps it in sync with the parent.
     */
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    label: text("label").notNull(),
    dueDate: date("due_date").notNull(),
    /**
     * Manual ordering for stages on the same date (rare but real:
     * "send docs request" + "schedule meeting" both due Mon). Service
     * layer assigns this on insert as MAX(sort_order)+1 within the
     * parent deadline. Sub-second precision on createdAt would also
     * work as a tie-breaker, but explicit sort lets the user reorder.
     */
    sortOrder: integer("sort_order").notNull().default(0),
    /**
     * Per-stage owner. Defaults to inheriting from the parent deadline's
     * owner_user_id at create time but the user can override per stage
     * (e.g. preparer does "draft return" / partner does "review").
     * NULL = inherits from deadline (display falls back to parent owner).
     */
    ownerUserId: text("owner_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    completedByUserId: text("completed_by_user_id").references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // Primary access pattern: list stages for a deadline (detail page,
    // dashboard progress bar). Composite (deadline, sort_order) lets us
    // ORDER BY without a sort step.
    index("deadline_subtasks_deadline_idx").on(
      t.deadlineInstanceId,
      t.sortOrder,
    ),
    // "Open stages I own" — for future C-3 notification system + sidebar
    // badge. Keep it cheap from day one.
    index("deadline_subtasks_org_owner_open_idx").on(
      t.orgId,
      t.ownerUserId,
      t.completedAt,
    ),
    // Dashboard "stages due in next 7 days" — by date, with org gate.
    index("deadline_subtasks_org_due_idx").on(t.orgId, t.dueDate),
  ],
);

// ---------------------------------------------------------------------------
// Reminders sent (dedupe — never send same 14-day reminder twice)
// ---------------------------------------------------------------------------

export const remindersSent = pgTable(
  "reminders_sent",
  {
    id: text("id").primaryKey().$defaultFn(() => `rem_${nanoid(12)}`),
    deadlineInstanceId: text("deadline_instance_id")
      .notNull()
      .references(() => deadlineInstances.id, { onDelete: "cascade" }),
    daysBeforeDue: integer("days_before_due").notNull(), // 30 | 14 | 3 | 1
    channel: text("channel").notNull(), // "email" for MVP, "sms" V2
    sentToEmail: text("sent_to_email"),
    sentAt: timestamp("sent_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("reminders_dedupe_idx").on(
      t.deadlineInstanceId,
      t.daysBeforeDue,
      t.channel,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Weekly digest sends (idempotent — second cron tick this week is a no-op)
//
// Identified by ISO week (e.g., "2026-W17") so the dedupe boundary lines
// up with how a CPA mentally schedules. If we change cadence later we
// can add a `digest_type` discriminator on the unique index.
// ---------------------------------------------------------------------------

export const digestSends = pgTable(
  "digest_sends",
  {
    id: text("id").primaryKey().$defaultFn(() => `dig_${nanoid(12)}`),
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    /** ISO 8601 week — e.g. "2026-W17". One digest per (user, week, type). */
    weekKey: text("week_key").notNull(),
    digestType: text("digest_type").notNull().default("weekly"),
    recipientEmail: text("recipient_email").notNull(),
    deadlineCount: integer("deadline_count").notNull().default(0),
    urgentCount: integer("urgent_count").notNull().default(0),
    /** AI-generated one-liner ("This week's heavier than usual…"). */
    aiSummary: text("ai_summary"),
    /** Resend message id, for clickthrough debugging. */
    providerMessageId: text("provider_message_id"),
    sentAt: timestamp("sent_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("digest_sends_user_week_idx").on(
      t.userId,
      t.weekKey,
      t.digestType,
    ),
    index("digest_sends_org_idx").on(t.orgId),
  ],
);

// ---------------------------------------------------------------------------
// In-app notifications — per-user popover feed (C-3).
//
// Sits alongside the email reminder pipeline, not in place of it. Every
// fire of /api/cron/reminders writes one row here AND one to remindersSent
// (channel="email"). The two tables play different roles:
//
//   - notifications powers the bell badge + popover. Per-user, dismissable,
//     denormalized title/body/link so the popover renders without a join.
//   - remindersSent is the email idempotency ledger ("did we already send
//     the T-3 reminder for this deadline?"). Independent so a user can mark
//     all read in the popover without re-triggering email sends, and an
//     email-disabled future user still gets the in-app feed.
//
// Recipient resolution lives in the cron, not the schema:
//   deadline_t_minus_{7,3,1}  → deadline.owner_user_id
//   stage_t_minus_1           → subtask.owner_user_id ?? deadline.owner_user_id
// (NULL stage owner = "inherits parent" per the deadlineSubtasks design,
// so reminder logic stays consistent with the display fallback rule.)
//
// Retention: no hard cap in v1. The popover query limits to ~50 most
// recent rows per user; older rows are dead weight but not wrong. A GC
// cron can be added later (cron tag 'notifications.gc') without touching
// any read path.
// ---------------------------------------------------------------------------

export const notificationKindEnum = pgEnum("notification_kind", [
  "deadline_t_minus_7",
  "deadline_t_minus_3",
  "deadline_t_minus_1",
  "stage_t_minus_1",
]);

export const notifications = pgTable(
  "notifications",
  {
    id: text("id").primaryKey().$defaultFn(() => `nfn_${nanoid(12)}`),
    /**
     * Denormalized for cheap row-level org isolation. Popover queries
     * filter on (user_id, org_id) directly without joining through
     * deadline_instances → entities → clients → orgs. Service layer keeps
     * this in sync with the parent deadline at insert time.
     */
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    /** Recipient. Cascade because deleting a user clears their bell. */
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    kind: notificationKindEnum("kind").notNull(),
    deadlineInstanceId: text("deadline_instance_id")
      .notNull()
      .references(() => deadlineInstances.id, { onDelete: "cascade" }),
    /**
     * Set only for stage_t_minus_1 rows; NULL for deadline_t_minus_*.
     * Cascade with the stage so removing a subtask drops the orphan
     * notification — a stage that no longer exists shouldn't keep
     * counting toward the bell badge.
     */
    subtaskId: text("subtask_id").references(() => deadlineSubtasks.id, {
      onDelete: "cascade",
    }),
    /**
     * Denormalized snapshot fields. Popover renders straight from this
     * row (no join). Renames on the source deadline/stage do not cascade
     * back into already-delivered notifications — acceptable lag, since
     * the row links out via linkPath for current state.
     *
     *   title     → "1120-S · Rodriguez & Associates"
     *   body      → "Due in 1 day · You"
     *   linkPath  → "/deadlines/dl_xxxxx"
     */
    title: text("title").notNull(),
    body: text("body").notNull(),
    linkPath: text("link_path").notNull(),
    deliveredAt: timestamp("delivered_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** NULL = unread (counts toward bell badge); set when user opens popover or "Mark all read". */
    readAt: timestamp("read_at", { withTimezone: true }),
  },
  (t) => [
    /**
     * Dedupe — a single (user, deadline, subtask, kind) combo should
     * only ever produce one row, even if cron retries. nullsNotDistinct
     * makes (user, deadline, NULL, deadline_t_minus_1) collide on retry
     * (default Postgres treats two NULLs as distinct, which would
     * silently allow duplicate deadline-tier rows). Uses unique()
     * constraint rather than uniqueIndex() because nullsNotDistinct is
     * only exposed on the constraint API in drizzle-orm 0.45.x.
     */
    unique("notifications_dedupe_idx")
      .on(t.userId, t.deadlineInstanceId, t.subtaskId, t.kind)
      .nullsNotDistinct(),
    /**
     * Bell badge: SELECT COUNT(*) WHERE user_id = ? AND read_at IS NULL.
     * Partial index keeps it tiny — only unread rows live in it, so the
     * count query is essentially O(badge_count) per user.
     */
    index("notifications_unread_idx")
      .on(t.userId, t.deliveredAt)
      .where(sql`${t.readAt} IS NULL`),
    /**
     * Popover list: ORDER BY delivered_at DESC LIMIT 50, scoped to user.
     * Covers both unread + recent-read. Org filter applied in WHERE.
     */
    index("notifications_user_recent_idx").on(t.userId, t.deliveredAt),
  ],
);

// ---------------------------------------------------------------------------
// Tax-authority announcements — IRS Newsroom + state DOR feeds.
//
// Org-agnostic on purpose: an IRS hurricane relief notice is identical
// for every CPA, so we store it once and let each org's UI compute
// "does this affect any of my clients?" on read by intersecting
// `affected_jurisdictions` with the org's clients' home states.
//
// Idempotency: `external_id` (RSS GUID / canonical link) is unique. The
// scrape workflow runs daily; second-run hits ON CONFLICT DO NOTHING.
// ---------------------------------------------------------------------------

export const announcements = pgTable(
  "announcements",
  {
    id: text("id").primaryKey().$defaultFn(() => `ann_${nanoid(12)}`),
    /** Origin feed — "irs_newsroom" today, state DORs in V2. */
    source: text("source").notNull(),
    /** RSS GUID or canonical URL — guaranteed unique per source. */
    externalId: text("external_id").notNull(),
    title: text("title").notNull(),
    summary: text("summary"),
    url: text("url").notNull(),
    publishedAt: timestamp("published_at", { withTimezone: true }).notNull(),

    /** AI classification — see ANNOUNCEMENT_CATEGORIES below. */
    category: text("category").notNull().default("general"),
    /** AI extraction — ["federal"] or ["FL", "TX"] or [] when unclear. */
    affectedJurisdictions: jsonb("affected_jurisdictions")
      .$type<string[]>()
      .notNull()
      .default([]),
    /** AI relevance score 1–5; bell only fires for >= 4. */
    relevanceScore: integer("relevance_score").notNull().default(3),
    /** AI one-line summary in CPA-friendly language. */
    aiSummary: text("ai_summary"),

    /**
     * Structured AI extraction layer (Round C).
     *
     * The original `affectedJurisdictions` (state codes only) is too
     * coarse — "FL hurricane" matched all FL clients including ones
     * who have no deadlines in the relief window. These four fields
     * narrow the match to exactly the affected work:
     *
     *   - affectedFormCodes: form codes the announcement specifically
     *     names (["1040", "1120", "941"]). Empty when "all returns".
     *   - originalDeadlineStart/End: ISO date range that the
     *     announcement is postponing (e.g. "deadlines from Aug 5
     *     through Feb 3"). NULL when not a date-postponement item.
     *   - reliefDeadline: the new postponed date (e.g. "moved to
     *     Feb 3, 2026"). NULL when not applicable.
     *
     * All four are nullable / empty by default so older rows still
     * work without backfill, and AI failures gracefully degrade to
     * the coarse state-only match.
     */
    affectedFormCodes: jsonb("affected_form_codes")
      .$type<string[]>()
      .notNull()
      .default([]),
    originalDeadlineStart: text("original_deadline_start"), // YYYY-MM-DD
    originalDeadlineEnd: text("original_deadline_end"),     // YYYY-MM-DD
    reliefDeadline: text("relief_deadline"),                // YYYY-MM-DD

    /**
     * The actual FEMA-declared disaster counties named in disaster
     * relief announcements. State-only matching ("clients in FL")
     * over-includes — IRS disaster relief is county-level (Hillsborough
     * County, FL is in scope, Pinellas County, FL might not be), and
     * a CPA in FL whose clients are nowhere near the disaster zone
     * shouldn't be told their clients are "affected".
     *
     * Format is free-form strings the AI lifts from the IRS text
     * (e.g. ["Hillsborough County, FL", "Manatee County, FL"]).
     * We don't try to match against client county data — the
     * entities table doesn't carry it yet — but we surface the
     * county list prominently in the UI so the CPA can verify each
     * client's location before applying relief.
     *
     * Empty for non-disaster announcements and when the AI couldn't
     * extract county scope.
     */
    affectedCounties: jsonb("affected_counties")
      .$type<string[]>()
      .notNull()
      .default([]),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("announcements_source_external_idx").on(
      t.source,
      t.externalId,
    ),
    index("announcements_published_idx").on(t.publishedAt),
    index("announcements_score_published_idx").on(
      t.relevanceScore,
      t.publishedAt,
    ),
  ],
);

export const ANNOUNCEMENT_CATEGORIES = [
  "disaster_relief", // IRS extends deadline for storm/wildfire victims
  "form_change",     // Form 1099-K threshold change, new schedule, etc.
  "procedural",      // E-file requirement, filing-method change
  "general",         // Everything else / lowest priority
] as const;

// ---------------------------------------------------------------------------
// Per-user dismiss state for announcements.
//
// Lets a CPA close an announcement they've read so it stops claiming
// dashboard real estate. Per-USER (not per-org) — for solo persona this
// is the same thing, and for multi-seat firms it's actually the right
// primitive (partner A's "I've read this" shouldn't hide it from
// partner B who hasn't).
//
// Source-of-truth announcements stay intact; this is purely a view filter.
// Reversible — un-dismiss simply deletes the row.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Per-client review state for an announcement.
//
// When a deadline-affecting IRS announcement ("FL hurricane disaster
// relief, deadline postponed") matches some of the org's clients, the
// CPA's actual workflow is: walk through each affected client one by
// one, decide what to do. This table tracks "I've reviewed Anderson
// for this announcement" so the CPA can come back tomorrow and pick
// up where they left off.
//
// Per-USER (not per-org). Per-ORG would mean partner A acking
// "reviewed" hides it from partner B who hasn't looked. Wrong primitive.
// ---------------------------------------------------------------------------

export const announcementClientAcks = pgTable(
  "announcement_client_acks",
  {
    id: text("id").primaryKey().$defaultFn(() => `ack_${nanoid(12)}`),
    userId: text("user_id").notNull().references(() => users.id, {
      onDelete: "cascade",
    }),
    announcementId: text("announcement_id").notNull().references(
      () => announcements.id,
      { onDelete: "cascade" },
    ),
    clientId: text("client_id").notNull().references(() => clients.id, {
      onDelete: "cascade",
    }),
    ackedAt: timestamp("acked_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("ann_client_ack_user_ann_client_idx").on(
      t.userId,
      t.announcementId,
      t.clientId,
    ),
    index("ann_client_ack_ann_user_idx").on(t.announcementId, t.userId),
  ],
);

export const announcementDismissals = pgTable(
  "announcement_dismissals",
  {
    id: text("id").primaryKey().$defaultFn(() => `dis_${nanoid(12)}`),
    userId: text("user_id").notNull().references(() => users.id, {
      onDelete: "cascade",
    }),
    announcementId: text("announcement_id").notNull().references(
      () => announcements.id,
      { onDelete: "cascade" },
    ),
    dismissedAt: timestamp("dismissed_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // One dismiss per (user, announcement). Repeat clicks are no-ops.
    uniqueIndex("announcement_dismissals_user_ann_idx").on(
      t.userId,
      t.announcementId,
    ),
    // Anti-join from announcements list filter.
    index("announcement_dismissals_user_idx").on(t.userId),
  ],
);

// ---------------------------------------------------------------------------
// Invitations — tokenized email-based invites for the lightweight team tier.
//
// V1 flow:
//   1. Owner/admin creates an invitation with email + role.
//   2. App generates a tokenized link (/invite/<token>) and shows it copyable.
//   3. Admin shares the link manually (Slack / email — V1 no email infra).
//   4. Invitee opens link → sign-up page with token in query string.
//   5. After Clerk sign-up, ensureUserAndOrg sees the token, finds the pending
//      invitation, attaches the new user to the target org with the target
//      role, and marks the invitation accepted.
//
// Email-match fallback: if an invited email signs up *without* the token
// (e.g. they lost the link), bootstrap still attaches them by matching their
// Clerk email against pending invitations for any org. The token is the
// canonical link; email match is the safety net.
// ---------------------------------------------------------------------------

export const invitations = pgTable(
  "invitations",
  {
    id: text("id").primaryKey().$defaultFn(() => `inv_${nanoid(12)}`),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    /** Stored lowercase to match against Clerk's email at signup time. */
    email: text("email").notNull(),
    role: membershipRoleEnum("role").notNull().default("member"),
    /**
     * URL-safe random. The /invite/<token> link resolves a pending invitation
     * even before the user has a Clerk session. Unique-indexed so the
     * unauthenticated lookup is a single B-tree hit.
     */
    token: text("token").notNull(),
    status: invitationStatusEnum("status").notNull().default("pending"),
    invitedByUserId: text("invited_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    acceptedByUserId: text("accepted_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("invitations_token_idx").on(t.token),
    index("invitations_org_status_idx").on(t.orgId, t.status),
    index("invitations_email_status_idx").on(t.email, t.status),
  ],
);

// ---------------------------------------------------------------------------
// Audit log (Day 1 — invisible to users in MVP, visible in V2 small-firm tier)
// ---------------------------------------------------------------------------

export const auditEvents = pgTable(
  "audit_events",
  {
    id: text("id").primaryKey().$defaultFn(() => `aud_${nanoid(16)}`),
    orgId: text("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    actorType: actorTypeEnum("actor_type").notNull(),
    actorId: text("actor_id"), // user_id OR agent identifier OR "cron"
    action: text("action").notNull(), // "client.created", "deadline.completed", etc.
    targetType: text("target_type").notNull(), // "client" | "entity" | "deadline_instance" | ...
    targetId: text("target_id").notNull(),
    payload: jsonb("payload").$type<Record<string, unknown>>(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("audit_events_org_time_idx").on(t.orgId, t.occurredAt),
    index("audit_events_target_idx").on(t.targetType, t.targetId),
  ],
);

// ---------------------------------------------------------------------------
// Type exports
// ---------------------------------------------------------------------------

export type Organization = typeof organizations.$inferSelect;
export type NewOrganization = typeof organizations.$inferInsert;
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Membership = typeof memberships.$inferSelect;
export type Client = typeof clients.$inferSelect;
export type NewClient = typeof clients.$inferInsert;
export type Entity = typeof entities.$inferSelect;
export type NewEntity = typeof entities.$inferInsert;
export type EntityElection = typeof entityElections.$inferSelect;
export type NewEntityElection = typeof entityElections.$inferInsert;
export type DeadlineRule = typeof deadlineRules.$inferSelect;
export type DeadlineInstance = typeof deadlineInstances.$inferSelect;
export type NewDeadlineInstance = typeof deadlineInstances.$inferInsert;
export type AuditEvent = typeof auditEvents.$inferSelect;
export type NewAuditEvent = typeof auditEvents.$inferInsert;
export type DigestSend = typeof digestSends.$inferSelect;
export type NewDigestSend = typeof digestSends.$inferInsert;
export type Announcement = typeof announcements.$inferSelect;
export type NewAnnouncement = typeof announcements.$inferInsert;
export type AnnouncementDismissal = typeof announcementDismissals.$inferSelect;
export type AnnouncementClientAck = typeof announcementClientAcks.$inferSelect;
export type ClientContact = typeof clientContacts.$inferSelect;
export type NewClientContact = typeof clientContacts.$inferInsert;
export type Invitation = typeof invitations.$inferSelect;
export type NewInvitation = typeof invitations.$inferInsert;
export type ServiceGroup = typeof serviceGroups.$inferSelect;
export type NewServiceGroup = typeof serviceGroups.$inferInsert;
export type EntityService = typeof entityServices.$inferSelect;
export type NewEntityService = typeof entityServices.$inferInsert;
export type Notification = typeof notifications.$inferSelect;
export type NewNotification = typeof notifications.$inferInsert;
/** Discrete notification tiers — keep in sync with notificationKindEnum. */
export type NotificationKind = (typeof notificationKindEnum.enumValues)[number];
